### ISSUE TITLE
"Протекли" абсолютные пути с именем пользователя

### ISSUE THREAD

**Issue by derunix** [annmuor/pshell#1]
https://github.com/annmuor/pshell/blob/a7bfc4c55fa2ef92b00f75a048a4ae4caeaa163b/Makefile#L60
https://github.com/annmuor/pshell/blob/a7bfc4c55fa2ef92b00f75a048a4ae4caeaa163b/Makefile#L63
И дальше в Makefile их полно

**Comment by annmuor** [comment]
Спасибо
